export const Subscribers = [
  {
    id: 1,
    profilePicture: "assets/person/ashishchanchlani.jpg",
    username: "Ashish Chanchlani",
  },
  {
    id: 2,
    profilePicture: "assets/person/cgmeetup.jpg",
    username: "CG Meetup",
  },
  {
    id: 3,
    profilePicture: "assets/person/cleverProgrammer.jpg",
    username: "Clever Programmers",
  },
  {
    id: 4,
    profilePicture: "assets/person/codeStepByStep.jpg",
    username: "Code Step by Step",
  },
  {
    id: 5,
    profilePicture: "assets/person/onlineTutorials.jpg",
    username: "Online Tutorials",
  },
  {
    id: 6,
    profilePicture: "assets/person/lamadev.jpg",
    username: "Lama Dev",
  },
  {
    id: 7,
    profilePicture: "assets/person/sandeepMaheshwari.jpg",
    username: "Sandeep Maheshwari",
  },
  {
    id: 8,
    profilePicture: "assets/person/shemaroo.jpg",
    username: "Shemaroo",
  },
  {
    id: 9,
    profilePicture: "assets/person/sonnysangha.jpg",
    username: "Sonny Sangha",
  },
  {
    id: 10,
    profilePicture: "assets/person/sony.jpg",
    username: "Sony",
  },
];

export const Posts = [
  {
    id: 1,
    profilePicture: "assets/person/ashishchanchlani.jpg",
    username: "Ashish Chanchlani",
    title: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "1 Year ago",
    views: "32K",
  },
  {
    id: 2,
    profilePicture: "assets/person/cgmeetup.jpg",
    username: "CG Meetup",
    title:
      "CGI Animated Short Film: by Short & Petit, Pascal Ferrere | CGMeetup",
    photo: "assets/post/2.jpeg",
    date: "2 Year ago",
    views: "2.1M",
  },
  {
    id: 3,
    profilePicture: "assets/person/cleverProgrammer.jpg",
    username: "Clever Programmers",
    title: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    views: "61K",
  },
  {
    id: 4,
    profilePicture: "assets/person/codeStepByStep.jpg",
    title: "Love For All, Hatred For None.",
    username: "Code Step by Step",
    photo: "assets/post/4.jpeg",
    date: "16 hours ago",
    views: "13K",
  },
  {
    id: 5,
    profilePicture: "assets/person/onlineTutorials.jpg",
    title: "Water Drops | Drawing with Html & CSS Only",
    username: "Online Tutorials",
    photo: "assets/post/5.jpeg",
    date: "5 Months ago",
    views: "231K",
  },
  {
    id: 6,
    profilePicture: "assets/person/lamadev.jpg",
    title: "Love For All, Hatred For None.",
    username: "Lama Dev",
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    views: "44K",
  },
  {
    id: 7,
    profilePicture: "assets/person/sandeepMaheshwari.jpg",
    username: "Sandeep Maheshwari",
    title: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "3 Month ago",
    views: "52K",
  },
  {
    id: 8,
    profilePicture: "assets/person/shemaroo.jpg",
    title: "Love For All, Hatred For None.",
    username: "Shemaroo",
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    views: "155K",
  },
  {
    id: 9,
    profilePicture: "assets/person/sonnysangha.jpg",
    username: "Sonny Sangha",
    title: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "1 Year ago",
    views: "7.3M",
  },
  {
    id: 10,
    profilePicture: "assets/person/sony.jpg",
    username: "Sony",
    photo: "assets/post/10.jpeg",
    title: "Love For All, Hatred For None.",
    date: "1 week ago",
    views: "104K",
  },
  {
    id: 1,
    profilePicture: "assets/person/ashishchanchlani.jpg",
    username: "Ashish Chanchlani",
    title: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "1 Year ago",
    views: "32K",
  },
  {
    id: 2,
    profilePicture: "assets/person/cgmeetup.jpg",
    username: "CG Meetup",
    title:
      "CGI Animated Short Film: by Short & Petit, Pascal Ferrere | CGMeetup",
    photo: "assets/post/2.jpeg",
    date: "2 Year ago",
    views: "2.1M",
  },
  {
    id: 3,
    profilePicture: "assets/person/cleverProgrammer.jpg",
    username: "Clever Programmers",
    title: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    views: "61K",
  },
  {
    id: 4,
    profilePicture: "assets/person/codeStepByStep.jpg",
    title: "Love For All, Hatred For None.",
    username: "Code Step by Step",
    photo: "assets/post/4.jpeg",
    date: "16 hours ago",
    views: "13K",
  },
  {
    id: 5,
    profilePicture: "assets/person/onlineTutorials.jpg",
    title: "Water Drops | Drawing with Html & CSS Only",
    username: "Online Tutorials",
    photo: "assets/post/5.jpeg",
    date: "5 Months ago",
    views: "231K",
  },
  {
    id: 6,
    profilePicture: "assets/person/lamadev.jpg",
    title: "Love For All, Hatred For None.",
    username: "Lama Dev",
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    views: "44K",
  },
  {
    id: 7,
    profilePicture: "assets/person/sandeepMaheshwari.jpg",
    username: "Sandeep Maheshwari",
    title: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "3 Month ago",
    views: "52K",
  },
  {
    id: 8,
    profilePicture: "assets/person/shemaroo.jpg",
    title: "Love For All, Hatred For None.",
    username: "Shemaroo",
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    views: "155K",
  },
  {
    id: 9,
    profilePicture: "assets/person/sonnysangha.jpg",
    username: "Sonny Sangha",
    title: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "1 Year ago",
    views: "7.3M",
  },
  {
    id: 10,
    profilePicture: "assets/person/sony.jpg",
    username: "Sony",
    photo: "assets/post/10.jpeg",
    title: "Love For All, Hatred For None.",
    date: "1 week ago",
    views: "104K",
  },

];

export const LikedVideos = [
  {
    id: 4,
    profilePicture: "assets/person/codeStepByStep.jpg",
    title: "Love For All, Hatred For None.",
    username: "Code Step by Step",
    photo: "assets/post/4.jpeg",
    date: "16 hours ago",
    views: "13K",
  },
  {
    id: 5,
    profilePicture: "assets/person/onlineTutorials.jpg",
    title: "Water Drops | Drawing with Html & CSS Only",
    username: "Online Tutorials",
    photo: "assets/post/5.jpeg",
    date: "5 Months ago",
    views: "231K",
  },
]

// export const WatchLaterVideos = [

// ]
